In [7]:
import numpy as np
a = np.random.randn(10,3)
print(a)
k=0
for i in range (10):
    b=abs(a[i][0])-0.5
    l=a[i][0]
    for j in range (3):
        m=abs(a[i][j])-0.5
        if m < b:
            l=a[i][j]
            b=abs(a[i][j])-0.5
    print (l)

[[-6.54271089e-01 -8.27702383e-01  1.73176949e-03]
 [ 1.87794858e+00 -7.46334524e-01  3.81225466e-01]
 [-1.72739541e+00 -2.49297700e-01  3.74064516e-01]
 [ 2.80906768e-01 -2.27788590e+00  5.26148010e-01]
 [ 5.87085921e-01  9.72447136e-03  7.67651229e-01]
 [ 9.12288326e-01 -4.18087655e-01  2.53061221e-01]
 [ 3.85886932e-01 -1.93345813e+00  1.31966500e+00]
 [ 1.03393083e-01 -8.21928146e-01 -3.36801078e-01]
 [ 1.31041887e+00 -1.32496895e+00  4.57120298e-01]
 [ 2.15447633e+00  4.80460187e-01  3.15706588e-01]]
0.0017317694881523746
0.3812254655559826
-0.2492977004927485
0.28090676810066273
0.009724471364801496
0.2530612207000443
0.3858869320879954
0.10339308291954319
0.4571202981968128
0.31570658756653575


In [46]:
import numpy as np
a = np.random.randn(6,6)
b=a.min (axis=0)
c=a.sum (axis=1)
for i in range (6):
    if b[i]!=0:
        l=c[i]/b[i]
        print(l)
    else:
        print("bad")

[[ 0.2289185  -0.12354431 -0.14968387 -0.11025226 -0.84272578 -0.82745213]
 [-0.08326826  0.70663364  1.01372548  0.44438644  1.40948145 -0.95860885]
 [ 0.11905442 -0.07614781 -1.32203492 -0.41466413 -0.1304657   0.52081919]
 [ 0.85342147 -2.23473877  1.07279315  1.35813177 -0.57032764 -0.62830586]
 [ 1.24790137  1.91141904  0.60990434  1.14086855  0.81213873  1.5443479 ]
 [-0.56933834 -3.22878374  0.63384253  0.81355561  0.84935719  0.55256096]]
[-1.82473984  2.5323499  -1.30343895 -0.14902588  7.26657994 -0.9488058 ]
[-0.56933834 -3.22878374 -1.32203492 -0.41466413 -0.84272578 -0.95860885]
3.2050183500786087
-0.7843045888510595
0.9859338290553504
0.35938938025030115
-8.62270994004906
0.9897736708712115


In [38]:
import numpy as np
x=np.array([6,2,0,3,0,0,5,7,0])
a=len(x)
for i in range (a):
    if x[i]==0:
        if i<a-1:
            c=x[i+1]
            v=x[i+1]
for i in range (a):
    if x[i]==0:
        if i<a-1:
            c=x[i+1]
            if v<c:
                v=c
print (v)

5


In [48]:
import numpy as np
x=np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in i:
    x[j]=x[j]+1
print (x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [50]:
from scipy.cluster.vq import whiten
import numpy as np
N=input()
M=input()
obs=np.random.randn(M,N)
k=input()
thresh=input()
book=np.random.randn(k,N)
whiten(obs)

array([[4.17944278, 2.69811351, 7.21248917],
       [3.29956009, 2.93273208, 9.33380951],
       [1.75976538, 0.7038557 , 7.21248917]])